### PR TITLE
Soap adapt to new savon

### PR DESCRIPTION
**Pull request by calo81**
@emuzis @Simbul @ngsmrk  @Joachim31415 
So the new incompatibility with Savon was the name of the Message based on the operation. As you can see in the comparison image.
screen shot 2014-10-01 at 11 11 22
So this PR sends the operation name for the message together with the action name, so the message name is not automatically picked from the action name, but instead explicitly set.
Who is your QA?

### CODE REVIEW

**Comment by ngsmrk** [comment]
Signed-off-by: @ngsmrk

**Comment by calo81** [comment]
@Htunc and this one :smiley:

**Comment by Htunc** [comment]
Signed-off-by: @Htunc :+1:

**Comment by Simbul** [comment]
@calo81 we ended up never merging this one in. I'm not sure I remember what was the initial driver for this change, do you?

We should probably close the PR unless it's still something we need to do.

**Comment by amar-shah** [comment]
@calo81I will be closing down this PR on Monday, unless you say so.

**Comment by calo81** [comment]
@amar-shah don't close this one (or close it but leave the branch), it is used by Elliott.

@Simbul Some of the actions called in the SOAP API of exact target didn't work with the original code. Things that were needed for Elliott interaction with the API which is a bit more involved than the rest of projects.... This Branch adapts the messages to the API.

It was never merged as (this I don't remember well) I think there was some incompatibilities that didn't work with Chopin... but it could be that it just wasn't tested thoroughly inside chopin.

So yeah, this branch is needed.. We can take on retesting it in Chopin to see if they are actually compatible.

**Comment by amar-shah** [comment]
@dcoxall can you please look into this and see what we can do to get this branch merged, as running a forked branch of code for 1 year is not good.

**Comment by amar-shah** [comment]
Elliott is no longer an active application so closing down this PR and deleting the branch.

**Pull request closed without merging**
