### PR TITLE
Support Marketing Cloud SDK V130

### PR DESCRIPTION
**Pull request by lukaso**
With simply business adjustments and loosening of restrictions on gems. Brings up to date with v1.3.0 of salesforce's version, which is the latest released. This can stop us tracking very old versions.

Connected to this PR: https://github.com/simplybusiness/Skynet/pull/52

### CODE REVIEW

**Comment by lukaso** [comment]
Would really like us to move to the latest (well, not quite master) version of MarketingCloudSDK, so we aren't tracking their improvements in a really out of date fork. Also, for our improvements, we should really offer PRs to get them into the main line.

**Comment by lukaso** [comment]
Due to bug/missing feature in Version Check action, will have to be disabled in order for this PR to be merged.

**Comment by pawelma** [comment]
Just out of curiosity, why we don't want to switch to the official FuelSDK version? What features our fork delivers over the master because it's ambiguous (at least to me).

**Review by rifkinni — APPROVED** [review]

**Comment by rifkinni** [comment]
Alright I did a thorough cross reference with https://github.com/salesforce-marketingcloud/FuelSDK-Ruby/compare/1.3.0...simplybusiness:v130 and no hold ups on my end! :shipit:

**Review by addersuk — APPROVED** [review]

**Comment by lukaso** [comment]
> Just out of curiosity, why we don't want to switch to the official FuelSDK version? What features our fork delivers over the master because it's ambiguous (at least to me).

I believe the only reason is that a failed triggered send doesn't return an error on the official version. In the future, if I have time, I will see if we can work around that, because I agree, having a fork is not great.

Were your changes to the authorization header done because of bugs, or just to improve it?

**Comment by pawelma** [comment]
> Were your changes to the authorization header done because of bugs, or just to improve it?

Both, because it worked with query params but only for CoCo and Chopin (those apps had special exception set on ET side). Any others were failing with that method. After the switch, all apps using v1 API are authorized properly.

**Pull request merged**
