### PR TITLE
[RTNRS-2609] Update ExactTarget triggered sends apis

### PR DESCRIPTION
**Pull request by JadeDickinson**
### What
- Updates SOAP API from deprecated version to tenant-specific version (see https://help.salesforce.com/s/articleView?id=000356497&type=1)
- Updates REST API from deprecated version to tenant-specific version (see https://help.salesforce.com/s/articleView?id=000356498&type=1)
- Bumps gem by a major version since the old endpoints will be deprecated in September 2022
- Ata from ECRM has provided the tenant-specific endpoints/URIs from ExactTarget

### Why
Currently used endpoints are to be deprecated in September.

### Implementation approach
I'm open to separating out the refactor commits to a separate PR if we want to lower the risk of this one.

N.B. I investigated getting us on the upstream gem. However, some tests that pass on our fork fail on the upstream, due to missing mocking.

In addition, the upstream gem uses the deprecated endpoints and so will not work come September.

### CODE REVIEW

**Review by VictorPS — APPROVED** [review]
LGTM 👍 
I just have one question, do we need to worry about these URIs getting exposed?

**Comment by JadeDickinson** [comment]
> LGTM 👍 I just have one question, do we need to worry about these URIs getting exposed?

Good question - I don't think so as we also pass in a client ID and client secret when using the MarketingCloud::Client - https://github.com/simplybusiness/chopin/blob/e1561682c603b011b76138d1564757a09e63dd64/config/initializers/skynet.rb#L19 - from what I can tell these are held in secrets already.

**Comment by jhonny-e-SB** [comment]
> the upstream gem uses the deprecated endpoints and so will not work come September.

isn't the upstream library the 'official' SDK?

**Comment by JadeDickinson** [comment]
> > the upstream gem uses the deprecated endpoints and so will not work come September.
> 
> isn't the upstream library the 'official' SDK?

Yep, it's really weird. It doesn't look like there's much active development - no commits this year.

There's an open issue mentioning the requirement to move to tenant-specific endpoints and no one from Salesforce has replied in over 7 months: https://github.com/salesforce-marketingcloud/FuelSDK-Ruby/issues/123

**Comment by addersuk** [comment]
Closing as archiving the repo

**Pull request closed without merging**
